# Generated by Django 5.0.6 on 2025-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socalfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socalfeed',
            name='about_block',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socalfeed',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socalfeed',
            name='block_by',
            field=models.CharField(default='Admin', max_length=5),
        ),
    ]
