# Generated by Django 5.0.6 on 2025-02-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0003_facilityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='anoumt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='check_responce',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration_unit',
            field=models.CharField(default='year', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
